### ISSUE TITLE
The plugin doesn't seem to be effective

### ISSUE THREAD

**Issue by reorx** [electrovir/prettier-plugin-multiline-arrays#9] opened 2022-04-02 17:06 UTC
Hi there, I really appreciate this plugin, I believe it could be a life-saver, but currently, I just cannot make it work.

I created an empty folder, add one file called `consts.ts` within:

```
const pl = [
  'prettier-plugin-sort-json', 'prettier-plugin-packagejson',
  'prettier-plugin-multiline-arrays', 'prettier-plugin-organize-imports', 'prettier-plugin-jsdoc',
]

// prettier-elements-per-line: 2 1
const availableTags = [
	'a', 'aside', 'b', 'blockquote', 'br', 'code', 'em', 'figcaption', 'figure', 'h3', 'h4', 'hr', 'i', 'iframe', 'img', 'li', 'ol', 'p', 'pre', 's', 'strong', 'u', 'ul', 'video',
	'table',
]
```

Install prettier and this plugin:

```
yarn add  prettier prettier-plugin-multiline-arrays --dev
```

Add the config file `.prettierrc.js`:

```
const prettierConfig = {
  plugins: [
      'prettier-plugin-multiline-arrays', // plugin added here
  ],
  printWidth: 100,
  singleQuote: true,
  tabWidth: 4,
  multilineArrayWrapThreshold: 3,
  multilineArrayElementsPerLine: "3",
};

module.exports = prettierConfig;

```

And then run prettier `yarn prettier const.ts`, but the result shows single line elements in array:

```
[debug] normalized argv: {"_":["./consts.ts"],"color":true,"editorconfig":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["./consts.ts"],"color":true,"editorconfig":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'consts.ts'
[debug] loaded options `{"plugins":["prettier-plugin-multiline-arrays"],"printWidth":100,"singleQuote":true,"tabWidth":4,"multilineArrayWrapThreshold":3,"multilineArrayElementsPerLine":"3"}`
[debug] applied config-precedence (cli-override): {"multilineArrayElementsPerLine":"3","multilineArrayWrapThreshold":3,"plugins":["prettier-plugin-multiline-arrays"],"printWidth":100,"singleQuote":true,"tabWidth":4}
const pl = [
    'prettier-plugin-sort-json',
    'prettier-plugin-packagejson',
    'prettier-plugin-multiline-arrays',
    'prettier-plugin-organize-imports',
    'prettier-plugin-jsdoc',
];

// prettier-elements-per-line: 2 1
const availableTags = [
    'a',
    'aside',
    'b',
    'blockquote',
    'br',
    'code',
    'em',
    'figcaption',
    'figure',
    'h3',
    'h4',
    'hr',
    'i',
    'iframe',
    'img',
    'li',
    'ol',
    'p',
    'pre',
    's',
    'strong',
    'u',
    'ul',
    'video',
    'table',
];
✨  Done in 1.15s.
```

I don't know what's wrong and how to fix, please help.

**Comment by electrovir** [comment] 2022-04-02 17:54
Try this in your `.prettierrc.js` file:

```
plugins: [
      './node_modules/prettier-plugin-multiline-arrays', // plugin added here
  ],
```

It seems this is a common enough error, I'll update it in the README. Hopefully this helps your case!

**Comment by reorx** [comment] 2022-04-03 02:09
Thanks for the help, however, the change still doesn't work, the output is the same as what I posted above.

And I think in both cases the plugin is loaded, because when I tried to use a invalid value for the option, the plugin will raise an error as below:

```
[debug] normalized argv: {"_":["./consts.ts"],"color":true,"editorconfig":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["./consts.ts"],"color":true,"editorconfig":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'consts.ts'
[debug] loaded options `{"plugins":["/Users/reorx/Code/test-prettier/node_modules/prettier-plugin-multiline-arrays"],"printWidth":100,"singleQuote":true,"tabWidth":4,"multilineArrayWrapThreshold":3,"multilineArrayElementsPerLine":3}`
[error] Invalid multilineArrayElementsPerLine value. Expected a string, but received 3.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by electrovir** [comment] 2022-04-03 16:23
Oh nice, good idea to check that. I'll investigate!

**Comment by electrovir** [comment] 2022-04-03 16:58
I'm sorry, I'm not able to reproduce this 😕

I created a separate repo for testing this case and found no issue: https://github.com/electrovir/multiline-array-testing

Maybe something else is wrong with your setup? With your prettier config, the `pl` should also be formatted differently due to your config value `multilineArrayElementsPerLine: "3"`, as can be seen in the test repo here: https://github.com/electrovir/multiline-array-testing/blob/main/const.ts

**Comment by electrovir** [comment] 2022-04-14 14:36
If you can provide more info I'll gladly help more! But with everything in here currently I can't help with this issue, so closing for now.

**Closed by electrovir** 2022-04-14 14:36 UTC
Labels: bug
